hotel-foundation-build:
  only:
    changes:
      - components/hotel-module/foundation/**/*
  stage: build
  script:
    - ./gradlew :components:hotel-module:foundation:build

hotel-foundation-deploy:
  only:
    changes:
      - components/hotel-module/foundation/**/*
  stage: deploy
  script:
    - ./gradlew :components:hotel-module:foundation:publishToMavenLocal

# ========================
hotel-bundle1-build:
  only:
    changes:
      - components/hotel-module/bundle1/**/*
  stage: build
  script:
    - ./gradlew :components:hotel-module:bundle1:build

hotel-bundle1-lint:
  only:
    changes:
      - components/hotel-module/bundle1/**/*
  stage: build
  script:
    - ./gradlew :components:hotel-module:bundle1:lintInhouse

hotel-bundle1-deploy:
  only:
    changes:
      - components/hotel-module/bundle1/**/*
  stage: deploy
  script:
    - ./gradlew :components:hotel-module:bundle1:publishToMavenLocal
# ========================
hotel-bundle2-build:
  only:
    changes:
      - components/hotel-module/bundle2/**/*
  stage: build
  script:
    - ./gradlew :components:hotel-module:bundle2:build

hotel-bundle2-deploy:
  only:
    changes:
      - components/hotel-module/bundle2/**/*
  stage: deploy
  script:
    - ./gradlew :components:hotel-module:bundle2:publishToMavenLocal
# ========================

hotel-daily-check:
  only:
    changes:
      - components/hotel-module/**/*
  stage: build
  script:
    - ./gradlew :components:hotel-module:main:fileCounter
    - ./gradlew :components:hotel-module:main:dangerousApiTask
#lint job
#hotelLint:
#  only:
#    - hotel
#  stage: build
#  script:
#    - ./gradlew -Pci --console=plain -PbuildDir=lint :components:hotel-module:main:lintDebug

#debugTests:
#  stage: test
#  script:
#    - ./gradlew -Pci --console=plain :app:testDebug



