#确保每次给到测试的包都是最新的
hotel-foundation-build:
  only:
    changes:
      - components/hotel-module/foundation/**/*
  stage: build
  script:
    - ./android/gradlew :components:hotel-module:foundation:assemble publishToMavenLocal includeBinaryModule  -PmoduleName=hotel-foundation
hotel-foundation-lint:
  only:
    changes:
      - components/hotel-module/foundation/**/*
  stage: build
  script:
    - ./android/gradlew :components:hotel-module:foundation:lintInhouse
#hotel-foundation-test:
#  only:
#    changes:
#      - components/hotel-module/bundle1/**/*
#  stage: test
#  script:
#    - ./android/gradlew :components:hotel-module:foundation:test
hotel-foundation-deploy1:
  only:
    changes:
      - components/hotel-module/foundation/**/*
  stage: deploy
  script:
    - ./android/gradlew :components:hotel-module:foundation:publishToMavenLocal #发布到远程仓库
hotel-foundation-deploy2:
  only:
    changes:
      - components/hotel-module/foundation/**/*
  stage: deploy
  script:
    - ./android/gradlew :components:hotel-module:bundle1:assemble publishToMavenLocal #发布到远程仓库

hotel-foundation-deploy3:
  only:
    changes:
      - components/hotel-module/foundation/**/*
  stage: deploy
  script:
    - ./android/gradlew :components:hotel-module:bundle2:assemble publishToMavenLocal #发布到远程仓库
# ========================
hotel-bundle1-build:
  only:
    changes:
      - components/hotel-module/bundle1/**/*
  stage: build
  script:
    - ./android/gradlew :components:hotel-module:bundle1:assemble

hotel-bundle1-lint:
  only:
    changes:
      - components/hotel-module/bundle1/**/*
  stage: build
  script:
    - ./android/gradlew :components:hotel-module:bundle1:lintInhouse

hotel-bundle1-deploy:
  only:
    changes:
      - components/hotel-module/bundle1/**/*
  stage: deploy
  script:
    - ./android/gradlew :components:hotel-module:bundle1:publishToMavenLocal #发布到远程仓库
# ========================
hotel-bundle2-build:
  only:
    changes:
      - components/hotel-module/bundle2/**/*
  stage: build
  script:
    - ./android/gradlew :components:hotel-module:bundle2:assemble

hotel-bundle2-lint:
  only:
    changes:
      - components/hotel-module/bundle2/**/*
  stage: build
  script:
    - ./android/gradlew :components:hotel-module:bundle2:lintInhouse

hotel-bundle2-deploy:
  only:
    changes:
      - components/hotel-module/bundle2/**/*
  stage: deploy
  script:
    - ./android/gradlew :components:hotel-module:bundle2:publishToMavenLocal
# ========================

hotel-daily-check1:
  only:
    changes:
      - components/hotel-module/**/*
  stage: build
  script:
    - ./android/gradlew :components:hotel-module:main:fileCounter
hotel-daily-check2:
  only:
    changes:
      - components/hotel-module/**/*
  stage: build
  script:
    - ./android/gradlew :components:hotel-module:main:dangerousApiTask
#lint job
#hotelLint:
#  only:
#    - hotel
#  stage: build
#  script:
#    - ./android/gradlew -Pci --console=plain -PbuildDir=lint :components:hotel-module:main:lintDebug

#debugTests:
#  stage: test
#  script:
#    - ./android/gradlew -Pci --console=plain :app:testDebug



