home-myhome-build:
  only:
    changes:
      #      - components/home-module/myhome/*.{java,kt,xml,gradle}
      - android/components/home-module/myhome/**/*
  stage: build
  script:
    - ./gradlew includeSourceModule  -PmoduleList=home-myhome
    - ./gradlew :components:home-module:myhome:assemble


home-myhome-lint:
  only:
    changes:
      - android/components/home-module/myhome/**/*
  stage: test
  script:
    - ./gradlew includeSourceModule  -PmoduleList=home-myhome
    - ./gradlew :components:home-module:myhome:lintInhouse

home-myhome-deploy:
  only:
    changes:
      - android/components/home-module/myhome/**/*
  stage: deploy
  script:
    - ./gradlew includeSourceModule  -PmoduleList=home-myhome
    - ./gradlew :components:home-module:myhome:publishAarPublicationToMavenCentralRepository #发布到远程仓库

## ========================
home-daily-check1:
  only:
    changes:
      - android/components/home-module/**/*
  stage: build
  script:
    - ./gradlew includeSourceModule  -PmoduleList=home-myhome,home-main
    - ./gradlew :components:home-module:main:fileCounter
home-daily-check2:
  only:
    changes:
      - android/components/home-module/**/*
  stage: build
  script:
    - ./gradlew includeSourceModule  -PmoduleList=home-myhome,home-main
    - ./gradlew :components:home-module:main:dangerousApiTask

##debugTests:
##  stage: test
##  script:
##    - ./gradlew -Pci --console=plain :app:testDebug
#