# 确保fwk每个修改点都输出最新的fwk包给上层
fwk-common:
  only:
    changes:
      - framework/common/**/*
  stage: build
  script:
    - ./gradlew :framework:common:assemble publishToMavenLocal includeBinaryModule  -PmoduleName=framework-common
    # todo:并发执行 av hybrid image map storage network
#    #upload mave
    - ./gradlew :framework:av:assemble publishToMavenLocal includeBinaryModule  -PmoduleName=framework-av
#    #upload mave
    - ./gradlew :framework:hybrid:assemble publishToMavenLocal includeBinaryModule  -PmoduleName=framework-hybrid
#    #upload mave
    - ./gradlew :framework:image:assemble publishToMavenLocal includeBinaryModule  -PmoduleName=framework-image
#    #upload mave
#    - ./gradlew :framework:map:assemble publishToMavenLocal includeBinaryModule  -PmoduleName=framework-map
#    #upload mave
    - ./gradlew :framework:network:assemble publishToMavenLocal includeBinaryModule  -PmoduleName=framework-network
#    #upload mave
    - ./gradlew :framework:storage:assemble publishToMavenLocal includeBinaryModule  -PmoduleName=framework-storage
#    #upload mave
    - ./gradlew :framework:loader:assemble publishToMavenLocal
# ========================
fwk-av:
  only:
    changes:
      - framework/av/**/*
  stage: build
  script:
    - ./gradlew :framework:av:assemble publishToMavenLocal includeBinaryModule  -PmoduleName=framework-av
    - ./gradlew :framework:loader:assemble publishToMavenLocal
# ========================
#fwk-flutter:
#  only:
#    changes:
#      - framework/flutter/**/*
#  stage: build
#  script:
#    - ./gradlew :framework:flutter:build
# ========================
fwk-hybrid:
  only:
    changes:
      - framework/hybrid/**/*
  stage: build
  script:
    - ./gradlew :framework:hybrid:assemble publishToMavenLocal includeBinaryModule  -PmoduleName=framework-hybrid
    - ./gradlew :framework:loader:assemble publishToMavenLocal
# ========================
fwk-image:
  only:
    changes:
      - framework/image/**/*
  stage: build
  script:
    - ./gradlew :framework:image:assemble publishToMavenLocal includeBinaryModule  -PmoduleName=framework-image
    - ./gradlew :framework:loader:assemble publishToMavenLocal
# ========================
#fwk-map:
#  only:
#    changes:
#      - framework/map/**/*
#  stage: build
#  script:
#    - ./gradlew :framework:map:assemble publishToMavenLocal includeBinaryModule  -PmoduleName=framework-map
#    - ./gradlew :framework:loader:assemble publishToMavenLocal
# ========================
#fwk-mockserver:
#  only:
#    changes:
#      - framework/mockserver
#  stage: build
#  script:
#    - ./gradlew :framework:mockserver:build
#     - ./gradlew :framework:loader:assemble
# ========================
fwk-network:
  only:
    changes:
      - framework/network/**/*
  stage: build
  script:
    - ./gradlew :framework:network:assemble publishToMavenLocal includeBinaryModule  -PmoduleName=framework-network
    - ./gradlew :framework:loader:assemble publishToMavenLocal
# ========================
fwk-storage:
  only:
    changes:
      - framework/storage/**/*
  stage: build
  script:
    - ./gradlew :framework:storage:assemble publishToMavenLocal includeBinaryModule  -PmoduleName=framework-storage
    - ./gradlew :framework:loader:assemble publishToMavenLocal
# ========================
fwk-loader:
  only:
    changes:
      - framework/loader/**/*
  stage: build
  script:
    - ./gradlew :framework:loader:assemble publishToMavenLocal
# ========================
#buildBigApp job
#build-big-app:
#  stage: build
#  script:
#    - ./gradlew buildBigApp
#  #    - ./gradlew reportMappingDebug  &&  ./gradlew reportSoDebug
#  artifacts:
#    paths:
#      - app/build/outputs/app-release.apk
#dailyCheck:
#  only:
#    - master
#  stage: build
#  script:
#    #    - ./gradlew :app:fileCounter
#    - ./gradlew :app:dangerousApiTask
#deploy2Firebase:
#  only:
#    - master
#  stage: deploy
#  script:
#    - ./gradlew :app:appDistributionUploadRelease
#deploy2Pgyer:
#  only:
#    - master
#  stage: deploy
#  script:
#    - ./script/pgyer_upload.sh "${CI_PROJECT_DIR}/app/build/outputs/apk/release/app-release.apk" $PG_API_KEY $PG_APP_KEY ${CI_PROJECT_DIR}
#    - echo "deploy to pgyer"
# ========================


#lint job
#lintDebug:
#  only:
#    - master
#  stage: build
#  #  before_script:#会覆盖最外层的before_script流程
#  #    - echo "lint before script"
#  script:
#    - ./gradlew -Pci --console=plain -PbuildDir=lint :app:lintDebug

#debugTests:
#  stage: test
#  script:
#    - ./gradlew -Pci --console=plain :app:testDebug

#docker build:
#  script: docker build -t my-image:$CI_COMMIT_REF_SLUG .
#  only:
#    changes:
#      - Dockerfile #The Dockerfile file
#      - docker/scripts/* #Any of the files inside docker/scripts/ directory.
#      - dockerfiles/**/*  #Any of the files and subdirectories inside the dockerfiles directory.
#      - more_scripts/*.{rb,py,sh} #Any of the files with rb, py, sh extensions inside the more_scripts directory.