#确保每次给到测试的包都是最新的
hotel-foundation:
  only:
    changes:
      - android/components/hotel-module/foundation/**/*
  stage: build
  script:
    - ./gradlew includeSourceModule  -PmoduleList=hotel-foundation
    - ./gradlew :components:hotel-module:foundation:assemble publishAarPublicationToMavenCentralRepository
hotel-foundation-lint:
  only:
    changes:
      - android/components/hotel-module/foundation/**/*
  stage: test
  script:
    - ./gradlew includeSourceModule  -PmoduleList=hotel-foundation
    - ./gradlew :components:hotel-module:foundation:lintInhouse
#hotel-foundation-test:
#  only:
#    changes:
#      - android/components/hotel-module/bundle1/**/*
#  stage: test
#  script:
#    - ./gradlew :components:hotel-module:foundation:test
# ========================
hotel-bundle1:
  only:
    changes:
      - android/components/hotel-module/bundle1/**/*
  stage: build
  script:
    - ./gradlew includeSourceModule  -PmoduleList=hotel-bundle1
    - ./gradlew :components:hotel-module:bundle1:assemble publishAarPublicationToMavenCentralRepository

hotel-bundle1-lint:
  only:
    changes:
      - android/components/hotel-module/bundle1/**/*
  stage: test
  script:
    - ./gradlew includeSourceModule  -PmoduleList=hotel-bundle1
    - ./gradlew :components:hotel-module:bundle1:lintInhouse

# ========================
hotel-bundle2:
  only:
    changes:
      - android/components/hotel-module/bundle2/**/*
  stage: build
  script:
    - ./gradlew includeSourceModule  -PmoduleList=hotel-bundle2
    - ./gradlew :components:hotel-module:bundle2:assemble publishAarPublicationToMavenCentralRepository

hotel-bundle2-lint:
  only:
    changes:
      - android/components/hotel-module/bundle2/**/*
  stage: test
  script:
    - ./gradlew includeSourceModule  -PmoduleList=hotel-bundle2
    - ./gradlew :components:hotel-module:bundle2:lintInhouse
# ========================

hotel-daily-check1:
  only:
    changes:
      - android/components/hotel-module/**/*
  stage: build
  script:
    - ./gradlew includeSourceModule  -PmoduleList=hotel-bundle2,hotel-bunlde1,hotel-main,hotel-foundation
    - ./gradlew :components:hotel-module:main:fileCounter
hotel-daily-check2:
  only:
    changes:
      - android/components/hotel-module/**/*
  stage: build
  script:
    - ./gradlew includeSourceModule  -PmoduleList=hotel-bundle2,hotel-bunlde1,hotel-main,hotel-foundation
    - ./gradlew :components:hotel-module:main:dangerousApiTask
#lint job
#hotelLint:
#  only:
#    - hotel
#  stage: build
#  script:
#    - ./gradlew -Pci --console=plain -PbuildDir=lint :components:hotel-module:main:lintDebug

#debugTests:
#  stage: test
#  script:
#    - ./gradlew -Pci --console=plain :app:testDebug



