#确保每次给到测试的包都是最新的
hotel-foundation-build:
  only:
    changes:
      - android/components/hotel-module/foundation/**/*
  stage: build
  script:
#    - ./gradlew includeSourceModule  -PmoduleName=hotel-foundation
    - ./gradlew :components:hotel-module:foundation:assemble
hotel-foundation-lint:
  only:
    changes:
      - android/components/hotel-module/foundation/**/*
  stage: build
  script:
    - ./gradlew :components:hotel-module:foundation:lintInhouse
#hotel-foundation-test:
#  only:
#    changes:
#      - android/components/hotel-module/bundle1/**/*
#  stage: test
#  script:
#    - ./gradlew :components:hotel-module:foundation:test
hotel-foundation-deploy:
  only:
    changes:
      - android/components/hotel-module/foundation/**/*
  stage: deploy
  script:
    - ./gradlew :components:hotel-module:foundation:publishAarPublicationToMavenCentralRepository #发布到远程仓库
# ========================
hotel-bundle1-build:
  only:
    changes:
      - android/components/hotel-module/bundle1/**/*
  stage: build
  script:
#    - ./gradlew includeSourceModule  -PmoduleName=hotel-bundle1
    - ./gradlew :components:hotel-module:bundle1:assemble

hotel-bundle1-lint:
  only:
    changes:
      - android/components/hotel-module/bundle1/**/*
  stage: build
  script:
    - ./gradlew :components:hotel-module:bundle1:lintInhouse

hotel-bundle1-deploy:
  only:
    changes:
      - android/components/hotel-module/bundle1/**/*
  stage: deploy
  script:
    - ./gradlew :components:hotel-module:bundle1:publishAarPublicationToMavenCentralRepository #发布到远程仓库
# ========================
hotel-bundle2-build:
  only:
    changes:
      - android/components/hotel-module/bundle2/**/*
  stage: build
  script:
#    - ./gradlew includeSourceModule  -PmoduleName=hotel-bundle2
    - ./gradlew :components:hotel-module:bundle2:assemble

hotel-bundle2-lint:
  only:
    changes:
      - android/components/hotel-module/bundle2/**/*
  stage: build
  script:
    - ./gradlew :components:hotel-module:bundle2:lintInhouse

hotel-bundle2-deploy:
  only:
    changes:
      - android/components/hotel-module/bundle2/**/*
  stage: deploy
  script:
    - ./gradlew :components:hotel-module:bundle2:publishAarPublicationToMavenCentralRepository
# ========================

hotel-daily-check1:
  only:
    changes:
      - android/components/hotel-module/**/*
  stage: build
  script:
    - ./gradlew :components:hotel-module:main:fileCounter
hotel-daily-check2:
  only:
    changes:
      - android/components/hotel-module/**/*
  stage: build
  script:
    - ./gradlew :components:hotel-module:main:dangerousApiTask
#lint job
#hotelLint:
#  only:
#    - hotel
#  stage: build
#  script:
#    - ./gradlew -Pci --console=plain -PbuildDir=lint :components:hotel-module:main:lintDebug

#debugTests:
#  stage: test
#  script:
#    - ./gradlew -Pci --console=plain :app:testDebug



